# Generated by Django 5.0.1 on 2024-02-12 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the account.')),
                ('account_type', models.IntegerField(choices=[(1, 'Unknown'), (2, 'Bank Account'), (3, 'Credit Card'), (4, 'Cash')], default=1)),
                ('currency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency', verbose_name='Currency of the account.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Owner of the account.')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=256)),
                ('memo', models.CharField(max_length=256)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('transaction_type', models.IntegerField(choices=[(1, 'Debit'), (2, 'Credit')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='The account on which this transaction was operated.')),
            ],
        ),
    ]
