# Generated by Django 5.0.1 on 2024-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_hash',
            field=models.UUIDField(default=2, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.CharField(max_length=128),
        ),
    ]
