# Generated by Django 5.0.1 on 2024-02-12 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('identifier', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='3 characters identifier of a currency')),
                ('symbol', models.CharField(max_length=1, verbose_name='Visual representation of the currency')),
            ],
        ),
    ]
