# Generated by Django 5.0.1 on 2024-02-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32, verbose_name='First name of an user.')),
                ('lastName', models.CharField(max_length=32, verbose_name='Last name of an user.')),
            ],
        ),
    ]
